// packages/vue-freezeframe/src/App.vue
<template>
  <div id="app">
    <p class="bold title">vue-freezeframe</p>

    <div class="section">
      <p>basic,<br />animate on hover.</p>

      <vue-freezeframe
        src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e9ccec212d9451d56ff9/1519814094696/Lincoln_Cinemagraph_615.gif?format=1000w"
        @toggle="(e, items, isPlaying) => logEvent('toggle', e, items, isPlaying)"
        @start="(e, items, isPlaying) => logEvent('start', e, items, isPlaying)"
        @stop="(e, items, isPlaying) => logEvent('stop', e, items, isPlaying)"
      />
    </div>

    <div class="section">
      <p>start/stop manually, with overlay</p>

      <button @click="start">Start</button>
      <button @click="stop">Stop</button>
      <button @click="toggle">Toggle</button>

      <vue-freezeframe
        src="http://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/55f96e21e4b0f86680e762dc/56aa551b8b38d446e39e933b/1454003533097/.gif"
        ref="freeze"
        :options="{
          trigger: false,
          overlay: true,
        }"
        @toggle="(e, items, isPlaying) => logEvent('toggle', e, items, isPlaying)"
        @start="(e, items, isPlaying) => logEvent('start', e, items, isPlaying)"
        @stop="(e, items, isPlaying) => logEvent('stop', e, items, isPlaying)"
      />
    </div>

    <div class="section">
      <p>using slot & overlay</p>

      <vue-freezeframe class="grid" :options="{ overlay: true }">
        <div class="cell">
          <img
            src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e801085229b264ca29fc/1519577337605/download.gif?format=1000w"
          />
        </div>
        <div class="cell">
          <img
            src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e904c830257a34734ff5/1519577373504/Armani-Central-Park-6151.gif?format=1000w"
          />
        </div>
        <div class="cell">
          <img
            src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a95c231419202eb9a763970/1519814094692/tumblr_nfro6qnt591qzcq51o1_500.gif?format=750w"
          />
        </div>
        <div class="cell">
          <img
            src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a93f42471c10b0d656d1562/1519814094495/dirk-980.gif?format=1000w"
          />
        </div>
      </vue-freezeframe>
    </div>

    <div class="section">
      <p>destroy, remove event listeners</p>

      <button @click="visible = false">Destroy</button>

      <vue-freezeframe
        v-if="visible"
        src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e9ccec212d9451d56ff9/1519814094696/Lincoln_Cinemagraph_615.gif?format=1000w"
        @toggle="(e, items, isPlaying) => logEvent('toggle', e, items, isPlaying)"
        @start="(e, items, isPlaying) => logEvent('start', e, items, isPlaying)"
        @stop="(e, items, isPlaying) => logEvent('stop', e, items, isPlaying)"
      />
    </div>

    <p>cinemagraphs by <a href="http://www.cinemagraphs.com/">cinemagraphs.com</a></p>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator'
import { Freeze, FreezeframeEvent } from 'freezeframe/types'
import VueFreezeframe from './components/VueFreezeframe.vue'

@Component({
  components: {
    VueFreezeframe,
  },
})
export default class App extends Vue {
  visible = true

  $refs!: {
    freeze: VueFreezeframe
  }

  toggle() {
    this.$refs.freeze.toggle()
  }

  start() {
    this.$refs.freeze.start()
  }

  stop() {
    this.$refs.freeze.stop()
  }

  logEvent(event: FreezeframeEvent, items: Freeze[], isPlaying: boolean) {
    console.log('Event emitted:', event, items, isPlaying); // eslint-disable-line
  }
}
</script>

<style lang="scss">
body {
  max-width: 1000px;
  margin: 0px auto;
  padding: 20px;
  font-size: 13px;
  text-align: center;
  color: #202020;
}
</style>

<style lang="scss" scoped>
a {
  color: #202020;
}

p {
  padding: 10px 0px;
  text-align: center;
  font-family: monospace;
}

button {
  width: 100px;
  margin: 0px 10px 10px 0px;
  padding: 5px 0px;
  border: 1px solid #000;
  background: #fff;
  outline: none;
  font-family: monospace;
  text-align: center;
}

button:active {
  background: #000;
  color: #fff;
}

.bold {
  font-weight: 700;
}

.italic {
  font-style: italic;
}

.grid {
  display: flex;
  flex-wrap: wrap;
  justify-items: center;
  align-items: center;

  .cell {
    width: calc(50% - 24px);
    height: auto;
    padding: 12px;
  }
}
</style>

// packages/angular-freezeframe/src/app/app.component.ts
import { Component, ViewChild } from '@angular/core';
import { AngularFreezeframeComponent } from '../../projects/angular-freezeframe/src/lib/angular-freezeframe.component'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-freezeframe-demo';

  @ViewChild('freeze') freeze!: AngularFreezeframeComponent

  start() {
    this.freeze?.start()
  }

  stop() {
    this.freeze?.stop()
  }

  toggle() {
    this.freeze?.toggle()
  }
}

<div>
  <p class="bold title">angular-freezeframe</p>

  <div class="section">
    <p>basic,<br />animate on hover.</p>
    <angular-freezeframe
      src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e9ccec212d9451d56ff9/1519814094696/Lincoln_Cinemagraph_615.gif?format=1000w"
    ></angular-freezeframe>
  </div>

  <div class="section">
    <p>start/stop manually, with overlay</p>

    <button (click)="start()">Start</button>
    <button (click)="stop()">Stop</button>
    <button (click)="toggle()">Toggle</button>

    <angular-freezeframe
      src="http://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/55f96e21e4b0f86680e762dc/56aa551b8b38d446e39e933b/1454003533097/.gif"
      #freeze
      [options]="{
        trigger: false,
        overlay: true
      }"
    ></angular-freezeframe>
  </div>

  <div class="section">
    <p>using children & overlay</p>

    <angular-freezeframe
      [options]="{
        overlay: true
      }"
    >
      <div class="grid">
        <div class="cell">
          <img src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e801085229b264ca29fc/1519577337605/download.gif?format=1000w" alt="" />
        </div>
        <div class="cell">
          <img src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e904c830257a34734ff5/1519577373504/Armani-Central-Park-6151.gif?format=1000w" alt="" />
        </div>
        <div class="cell">
          <img src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a95c231419202eb9a763970/1519814094692/tumblr_nfro6qnt591qzcq51o1_500.gif?format=750w" alt="" />
        </div>
        <div class="cell">
          <img src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a93f42471c10b0d656d1562/1519814094495/dirk-980.gif?format=1000w" alt="" />
        </div>
      </div>
    </angular-freezeframe>
  </div>

  <!-- <div class="section">
    <p>destroy, remove event listeners</p>

    <button onClick={() => this.destroy()}>Destroy</button>

    { this.state?.visible && <ReactFreezeframe
      src="https://static1.squarespace.com/static/51c748abe4b0c275d0aa86bf/5a9298a1c830257a3467a8de/5a92e9ccec212d9451d56ff9/1519814094696/Lincoln_Cinemagraph_615.gif?format=1000w"
      onToggle={(items, isPlaying) => this.logEvent('toggle', items, isPlaying)}
      onStart={(items, isPlaying) => this.logEvent('start', items, isPlaying)}
      onStop={(items, isPlaying) => this.logEvent('stop', items, isPlaying)}
    />}
  </div> -->

  <p>cinemagraphs by <a href="http://www.cinemagraphs.com/">cinemagraphs.com</a></p>
</div>
